Repository cds-snc/resources-ressources, pull requests merged in 2022-08, with the labels that each got.

#166 [Release] Soft Launch - Add content security headers #165
  app/components/Box.vue
  app/components/Footer.vue
  app/components/Header.vue
  app/components/ResourceListItem.vue
  app/locales/en.json
  app/locales/fr.json
  app/nuxt.config.js
  customHttp.yml
Labels: Soft launch

#205 docs: add PR templates
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  pull_request_template.md
Labels: Documentation

#203 ci: add unsafe inline strict dynamic to support v-if
  customHttp.yml
Labels: Security | Sécurité

#208 fix: breadcrumbs accessibility
  app/components/Breadcrumbs.vue
Labels: Accessibility | Accessibilité, Front-end | Interface utilisateur

#231 Add staging link and release process
  infrastructure/README.md
  infrastructure/docs/architecture-aws-lr.drawio
  infrastructure/docs/architecture-aws-lr.png
Labels: Documentation
